<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'cf83cfbb35c2906067b083b4948dccdd',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/chess',
);
